name: Build branch
on:
  push:
    branches-ignore: [master]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v1
      - name: Docker login
        env:
          DOCKERHUB_ACCESS_TOKEN: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
        run: docker login --username arikkfir -p "${DOCKERHUB_ACCESS_TOKEN}"
      - name: Build ref mage
        run: docker build --tag=${GITHUB_REPOSITORY}:${GITHUB_SHA::7} .
      - name: Push ref image
        run: docker push ${GITHUB_REPOSITORY}:${GITHUB_SHA::7}
