name: CI
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v1
      - name: Docker login
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: docker login docker.pkg.github.com -u arikkfir -p "${GITHUB_TOKEN}"
      - name: Build Image
        run: docker build --tag=docker.pkg.github.com/${GITHUB_REPOSITORY}/neo4j:${GITHUB_SHA} .
      - name: Push Image
        run: docker push docker.pkg.github.com/${GITHUB_REPOSITORY}/neo4j:${GITHUB_SHA}
      - name: Push Image
        run: echo ${GITHUB_SHA::8}
