name: Build release
on:
  release:
    types: [published]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v1
      - name: Docker login
        env:
          DOCKERHUB_ACCESS_TOKEN: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
        run: docker login --username arikkfir -p "${DOCKERHUB_ACCESS_TOKEN}"
      - name: Pull ref image
        run: docker pull ${GITHUB_REPOSITORY}:${GITHUB_SHA::7}
      - name: Tag ref image as release image
        run: docker tag ${GITHUB_REPOSITORY}:${GITHUB_SHA::7} ${GITHUB_REPOSITORY}:$(cut -d'/' -f3 <<<${GITHUB_REF})
      - name: Push Image
        run: docker push ${GITHUB_REPOSITORY}:$(cut -d'/' -f3 <<<${GITHUB_REF})
